# cluster_config.yml - slurm farm cluster configuration
__default__:
    account: ctbrowngrp
    partition: med2
    mail-type: FAIL,TIME_LIMIT
    mail-user: ntpierce@ucdavis.edu
    time: 18:00:00
    nodes: 1
    ntasks-per-node: 1
    job-name: "{rule}"
    logdir: "/home/ntpierce/2021-jb-magsearch/slurm-logs"

